### PR TITLE
chore: pass compression options to `zstd.Encoder`

### PR DESCRIPTION
**Pull request by DmitriyMV**
This commit drastically decreases memory consumption in some cases.

### CODE REVIEW

**Review by smira — APPROVED** [review]
should we tie it into the Benchmark? I think I had one

And also might be nice to assert on the compression size.

But overall, great catch! :1st_place_medal:

**Comment by smira** [comment]
I think also part of that (I guess) is that it scales with `GOMAXPROCS`, and it runs on a machine with many cores.

**Comment by andrewrynhard** [comment]
I came here only to say that this is a `fix` ... but I don't expect you to change it here. Just something to keep in mind for other PRs. Chores are usually commits that don't have production code changes and are CI type changes.

**Comment by andrewrynhard** [comment]
> I came here only to say that this is a `fix` ... but I don't expect you to change it here. Just something to keep in mind for other PRs. Chores are usually commits that don't have production code changes and are CI type changes.

Other than that... awesome find!

**Pull request merged**
