### PR TITLE
feat: export controller-runtime cached state

### PR DESCRIPTION
**Pull request by smira**
Allow the consumer to take advantage of the cached state for Get/List operations.

### CODE REVIEW

**Comment by frezbo** [comment]
would this affect talos? like it gets cached data?

**Comment by smira** [comment]
> would this affect talos? like it gets cached data?

no, this is completely optional, just exposed the internal cache of the controller-runtime as state.State, it doesn't change anything if explicitly being used

**Review by Unix4ever — APPROVED** [review]

**Comment by smira** [comment]
Added some unit-tests

**Pull request merged**
